<?xml version="1.0" encoding="utf-8"?><Database Name="AssetManagement" Class="assetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CSCINDAE745733;Initial Catalog=AssetManagement;Integrated Security=True" SettingsObjectName="asset.datalayer.Properties.Settings" SettingsPropertyName="AssetManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AssetInfo" Member="AssetInfos">
    <Type Name="AssetInfo">
      <Column Name="asset_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="assetname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="emp_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="request_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="issueddate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Association Name="AssetInfo_TransferHistory" Member="TransferHistories" ThisKey="asset_id" OtherKey="asset_id" Type="TransferHistory" />
      <Association Name="RequestInfo_AssetInfo" Member="RequestInfo" ThisKey="request_id" OtherKey="request_id" Type="RequestInfo" IsForeignKey="true" />
      <Association Name="user_AssetInfo" Member="user" ThisKey="emp_id" OtherKey="emp_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RequestInfo" Member="RequestInfos">
    <Type Name="RequestInfo">
      <Column Name="request_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="emp_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="short_id" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="asset_name" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="manager_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="request_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="request_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="manager_approved_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="remarks" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="RequestInfo_AssetInfo" Member="AssetInfos" ThisKey="request_id" OtherKey="request_id" Type="AssetInfo" />
      <Association Name="user_RequestInfo" Member="user" ThisKey="emp_id" OtherKey="emp_id" Type="user" IsForeignKey="true" />
      <Association Name="user_RequestInfo1" Member="user1" ThisKey="short_id" OtherKey="short_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransferHistory" Member="TransferHistories">
    <Type Name="TransferHistory">
      <Column Name="transfer_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="from_emp_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="manager_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="asset_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="assetname" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="to_emp_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="transferdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="transferstatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="remarks" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="AssetInfo_TransferHistory" Member="AssetInfo" ThisKey="asset_id" OtherKey="asset_id" Type="AssetInfo" IsForeignKey="true" />
      <Association Name="user_TransferHistory" Member="user" ThisKey="from_emp_id" OtherKey="emp_id" Type="user" IsForeignKey="true" />
      <Association Name="user_TransferHistory1" Member="user1" ThisKey="manager_id" OtherKey="emp_id" Type="user" IsForeignKey="true" />
      <Association Name="user_TransferHistory2" Member="user2" ThisKey="to_emp_id" OtherKey="emp_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="emp_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="short_id" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="lname" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="email_id" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="user_password" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="manager_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="designation" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="mobile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_of_join" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="active" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Association Name="user_AssetInfo" Member="AssetInfos" ThisKey="emp_id" OtherKey="emp_id" Type="AssetInfo" />
      <Association Name="user_RequestInfo" Member="RequestInfos" ThisKey="emp_id" OtherKey="emp_id" Type="RequestInfo" />
      <Association Name="user_RequestInfo1" Member="RequestInfos1" ThisKey="short_id" OtherKey="short_id" Type="RequestInfo" />
      <Association Name="user_TransferHistory" Member="TransferHistories" ThisKey="emp_id" OtherKey="from_emp_id" Type="TransferHistory" />
      <Association Name="user_TransferHistory1" Member="TransferHistories1" ThisKey="emp_id" OtherKey="manager_id" Type="TransferHistory" />
      <Association Name="user_TransferHistory2" Member="TransferHistories2" ThisKey="emp_id" OtherKey="to_emp_id" Type="TransferHistory" />
    </Type>
  </Table>
</Database>