#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Supplier
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CSCDB")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProduct_Detail(Product_Detail instance);
    partial void UpdateProduct_Detail(Product_Detail instance);
    partial void DeleteProduct_Detail(Product_Detail instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CSCDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product_Detail> Product_Details
		{
			get
			{
				return this.GetTable<Product_Detail>();
			}
		}
		
		public System.Data.Linq.Table<supplier_info> supplier_infos
		{
			get
			{
				return this.GetTable<supplier_info>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product_Details")]
	public partial class Product_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prodid;
		
		private string _prodname;
		
		private int _supplierid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnprodidChanging(int value);
    partial void OnprodidChanged();
    partial void OnprodnameChanging(string value);
    partial void OnprodnameChanged();
    partial void OnsupplieridChanging(int value);
    partial void OnsupplieridChanged();
    #endregion
		
		public Product_Detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prodid", DbType="Int NOT NULL")]
		public int prodid
		{
			get
			{
				return this._prodid;
			}
			set
			{
				if ((this._prodid != value))
				{
					this.OnprodidChanging(value);
					this.SendPropertyChanging();
					this._prodid = value;
					this.SendPropertyChanged("prodid");
					this.OnprodidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prodname", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string prodname
		{
			get
			{
				return this._prodname;
			}
			set
			{
				if ((this._prodname != value))
				{
					this.OnprodnameChanging(value);
					this.SendPropertyChanging();
					this._prodname = value;
					this.SendPropertyChanged("prodname");
					this.OnprodnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supplierid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int supplierid
		{
			get
			{
				return this._supplierid;
			}
			set
			{
				if ((this._supplierid != value))
				{
					this.OnsupplieridChanging(value);
					this.SendPropertyChanging();
					this._supplierid = value;
					this.SendPropertyChanged("supplierid");
					this.OnsupplieridChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.supplier_info")]
	public partial class supplier_info
	{
		
		private int _supplierid;
		
		private string _suppliername;
		
		private string _supplier_address;
		
		private string _city;
		
		private System.Nullable<int> _contact_no;
		
		private string _email;
		
		public supplier_info()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supplierid", DbType="Int NOT NULL")]
		public int supplierid
		{
			get
			{
				return this._supplierid;
			}
			set
			{
				if ((this._supplierid != value))
				{
					this._supplierid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suppliername", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string suppliername
		{
			get
			{
				return this._suppliername;
			}
			set
			{
				if ((this._suppliername != value))
				{
					this._suppliername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supplier_address", DbType="VarChar(50)")]
		public string supplier_address
		{
			get
			{
				return this._supplier_address;
			}
			set
			{
				if ((this._supplier_address != value))
				{
					this._supplier_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(25)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="Int")]
		public System.Nullable<int> contact_no
		{
			get
			{
				return this._contact_no;
			}
			set
			{
				if ((this._contact_no != value))
				{
					this._contact_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(25)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
